import type { JSX } from 'react';
import { Box, Chip, Typography, List, ListItem, ListItemText } from '@mui/material';
import type { BreachInsight } from '@/core/ai/breachImpactExplain';

const RISK_COLOR: Record<BreachInsight['riskLevel'], 'success' | 'warning' | 'error'> = {
  low: 'success',
  medium: 'warning',
  high: 'error',
  critical: 'error',
};

export function BreachInsightCard({ insight }: { insight: BreachInsight }): JSX.Element {
  return (
    <Box sx={{ mt: 1, p: 1.5, border: 1, borderColor: 'divider', borderRadius: 1 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
        <Typography variant="subtitle2">Risk level</Typography>
        <Chip size="small" color={RISK_COLOR[insight.riskLevel]} label={insight.riskLevel} />
      </Box>
      {insight.exposedData.length > 0 && (
        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mb: 1 }}>
          {insight.exposedData.map((d) => (
            <Chip key={d} size="small" variant="outlined" label={d} />
          ))}
        </Box>
      )}
      {insight.steps.length > 0 && (
        <List dense>
          {insight.steps.map((s, i) => (
            <ListItem key={s} disableGutters>
              <ListItemText primary={`${String(i + 1)}. ${s}`} slotProps={{ primary: { variant: 'body2' } }} />
            </ListItem>
          ))}
        </List>
      )}
      <Typography variant="caption" color="text.disabled" display="block">Generated by on-device AI.</Typography>
    </Box>
  );
}
