import type { JSX } from 'react';
import { Box, Chip, Typography, List, ListItem, ListItemText } from '@mui/material';
import type { StrengthInsight } from '@/core/ai/strengthExplain';

const SEVERITY_COLOR: Record<StrengthInsight['severity'], 'success' | 'warning' | 'error'> = {
  low: 'success',
  medium: 'warning',
  high: 'error',
};

export function StrengthInsightCard({ insight }: { insight: StrengthInsight }): JSX.Element {
  return (
    <Box sx={{ mt: 1, p: 1.5, border: 1, borderColor: 'divider', borderRadius: 1 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
        <Typography variant="subtitle2">Severity</Typography>
        <Chip size="small" color={SEVERITY_COLOR[insight.severity]} label={insight.severity} />
      </Box>
      {insight.factors.map((f) => (
        <Typography key={f} variant="caption" color="text.secondary" display="block">• {f}</Typography>
      ))}
      {insight.rankedActions.length > 0 && (
        <List dense>
          {insight.rankedActions.map((a, i) => (
            <ListItem key={a} disableGutters>
              <ListItemText primary={`${String(i + 1)}. ${a}`} slotProps={{ primary: { variant: 'body2' } }} />
            </ListItem>
          ))}
        </List>
      )}
      <Typography variant="caption" color="text.disabled" display="block">Generated by on-device AI.</Typography>
    </Box>
  );
}
